# Generated by Django 4.2.7 on 2026-03-23 18:22

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('check_in_time', models.DateTimeField(db_index=True, verbose_name='check-in time')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='check-out time')),
                ('qr_code_scanned', models.CharField(blank=True, max_length=255, verbose_name='QR code scanned')),
                ('check_in_method', models.CharField(choices=[('qr', 'QR Code'), ('manual', 'Manual'), ('nfc', 'NFC'), ('face', 'Face Recognition')], default='qr', max_length=10, verbose_name='check-in method')),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'attendances',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('import', 'Import')], db_index=True, max_length=20, verbose_name='action type')),
                ('action', models.CharField(max_length=255, verbose_name='action description')),
                ('model_name', models.CharField(max_length=100, verbose_name='model name')),
                ('object_id', models.CharField(max_length=255, verbose_name='object ID')),
                ('object_repr', models.CharField(max_length=255, verbose_name='object representation')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('name', models.CharField(max_length=255, verbose_name='branch name')),
                ('code', models.CharField(blank=True, help_text='Short code for quick identification', max_length=20, verbose_name='branch code')),
                ('address', models.TextField(verbose_name='address')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ['gym', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('specialization', models.CharField(help_text='e.g., Yoga, Powerlifting, Nutrition', max_length=255, verbose_name='specialization')),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('qualifications', models.TextField(blank=True, verbose_name='qualifications')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='years of experience')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='hire date')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('salary_type', models.CharField(blank=True, max_length=20, verbose_name='salary type')),
                ('salary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='salary amount')),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text='JSON field for weekly schedule', verbose_name='working hours')),
            ],
            options={
                'verbose_name': 'coach profile',
                'verbose_name_plural': 'coach profiles',
                'ordering': ['-hire_date'],
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='gym name')),
                ('slug', models.SlugField(help_text='Used for subdomain routing and API endpoints', unique=True, verbose_name='slug')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='contact phone')),
                ('address', models.TextField(verbose_name='address')),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number for invoices', max_length=50, verbose_name='tax ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gym_logos/', verbose_name='logo')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='basic', max_length=20, verbose_name='subscription tier')),
            ],
            options={
                'verbose_name': 'gym',
                'verbose_name_plural': 'gyms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='phone number')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='profile image')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='gender')),
                ('join_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='join date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('qr_token', models.CharField(blank=True, db_index=True, help_text='Unique token for QR code generation', max_length=255, null=True, unique=True, verbose_name='QR token')),
                ('qr_code_image', models.ImageField(blank=True, help_text='Generated QR code image', null=True, upload_to='qr_codes/', verbose_name='QR code image')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, verbose_name='emergency contact name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='emergency contact phone')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, verbose_name='relation')),
                ('medical_notes', models.TextField(blank=True, verbose_name='medical notes')),
                ('allergies', models.TextField(blank=True, verbose_name='allergies')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to='core.branch', verbose_name='primary branch')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_profiles', to='core.gym', verbose_name='gym')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'member profile',
                'verbose_name_plural': 'member profiles',
                'ordering': ['-join_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='EGP', max_length=10, verbose_name='currency')),
                ('payment_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='payment date')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online Gateway'), ('mobile_money', 'Mobile Money')], db_index=True, max_length=20, verbose_name='payment method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partial', 'Partial')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('refund', 'Refund')], db_index=True, default='create', max_length=10, verbose_name='action type')),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='Gateway transaction ID', max_length=255, verbose_name='transaction ID')),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='receipt number')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.branch', verbose_name='branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.memberprofile', verbose_name='member')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('scheduled_start', models.DateTimeField(db_index=True, verbose_name='scheduled start time')),
                ('scheduled_end', models.DateTimeField(verbose_name='scheduled end time')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='actual start time')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='actual end time')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=20, verbose_name='status')),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True, verbose_name='calories burned')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (minutes)')),
                ('metrics_data', models.JSONField(blank=True, default=dict, verbose_name='metrics data')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='core.branch', verbose_name='branch')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_sessions', to='core.coachprofile', verbose_name='coach')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='core.memberprofile', verbose_name='member')),
            ],
            options={
                'verbose_name': 'workout session',
                'verbose_name_plural': 'workout sessions',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('name', models.CharField(max_length=255, verbose_name='plan name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('duration_days', models.PositiveIntegerField(help_text='Number of days the subscription is valid', verbose_name='duration (days)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('currency', models.CharField(default='EGP', max_length=10, verbose_name='currency')),
                ('max_checkins_per_day', models.PositiveIntegerField(default=1, verbose_name='max check-ins per day')),
                ('allows_guest', models.BooleanField(default=False, verbose_name='allows guest')),
                ('includes_coaching', models.BooleanField(default=False, verbose_name='includes coaching')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_popular', models.BooleanField(default=False, verbose_name='popular')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='core.gym', verbose_name='gym')),
            ],
            options={
                'verbose_name': 'subscription plan',
                'verbose_name_plural': 'subscription plans',
                'ordering': ['gym', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('start_date', models.DateField(db_index=True, verbose_name='start date')),
                ('end_date', models.DateField(db_index=True, verbose_name='end date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='auto-renew')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='cancellation reason')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='core.branch', verbose_name='purchasing branch')),
                ('initial_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initialized_subscription', to='core.payment', verbose_name='initial payment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.memberprofile', verbose_name='member')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.subscriptionplan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.subscription', verbose_name='subscription'),
        ),
        migrations.CreateModel(
            name='GymSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('allow_qr_checkin', models.BooleanField(default=True, verbose_name='allow QR check-in')),
                ('allow_ai_coaching', models.BooleanField(default=False, verbose_name='allow AI coaching')),
                ('allow_mobile_app', models.BooleanField(default=True, verbose_name='allow mobile app')),
                ('allow_online_payments', models.BooleanField(default=True, verbose_name='allow online payments')),
                ('allow_guest_checkins', models.BooleanField(default=False, verbose_name='allow guest check-ins')),
                ('currency', models.CharField(default='EGP', max_length=10, verbose_name='currency')),
                ('date_format', models.CharField(default='Y-m-d', max_length=20, verbose_name='date format')),
                ('timezone', models.CharField(default='Africa/Cairo', max_length=50, verbose_name='timezone')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='email notifications')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS notifications')),
                ('retention_days_attendance', models.PositiveIntegerField(default=365, verbose_name='attendance retention days')),
                ('retention_days_audit_log', models.PositiveIntegerField(default=730, verbose_name='audit log retention days')),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.gym', verbose_name='gym')),
            ],
            options={
                'verbose_name': 'gym settings',
                'verbose_name_plural': 'gym settings',
            },
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['slug', 'is_active'], name='core_gym_slug_6dc387_idx'),
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['created_at'], name='core_gym_created_85b207_idx'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='assigned_members',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='core.memberprofile', verbose_name='assigned members'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_profiles', to='core.branch', verbose_name='primary branch'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profiles', to='core.gym', verbose_name='gym'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='branch',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.gym', verbose_name='gym'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.gym', verbose_name='gym'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.memberprofile', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_attendances', to=settings.AUTH_USER_MODEL, verbose_name='scanned by'),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='gym_user_groups', related_query_name='gym_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.gym', verbose_name='gym'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='gym_user_permissions', related_query_name='gym_user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['member', 'scheduled_start'], name='core_workou_member__236db9_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['coach', 'scheduled_start'], name='core_workou_coach_i_6a475a_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['status'], name='core_workou_status_befbf5_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['branch', 'scheduled_start'], name='core_workou_branch__e157f2_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['gym', 'is_active'], name='core_subscr_gym_id_cb4118_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['gym', 'price'], name='core_subscr_gym_id_a8863e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('gym', 'name')},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['member', 'status'], name='core_subscr_member__5e1b80_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date'], name='core_subscr_end_dat_e6cd6f_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['start_date', 'end_date'], name='core_subscr_start_d_c1a727_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['member', 'start_date', 'end_date'], name='core_subscr_member__077d44_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='subscription_end_date_after_start_date'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['member', 'payment_date'], name='core_paymen_member__4adec8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'payment_date'], name='core_paymen_status_fdd89f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='core_paymen_transac_e8c2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['receipt_number'], name='core_paymen_receipt_f19e07_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_by', 'payment_date'], name='core_paymen_created_adb32c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['action_type', 'created_at'], name='core_paymen_action__d6760c_idx'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['gym', 'status'], name='core_member_gym_id_fd35a6_idx'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['user', 'gym'], name='core_member_user_id_0a6ece_idx'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['phone', 'gym'], name='core_member_phone_a90d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['qr_token'], name='core_member_qr_toke_18c80b_idx'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['gym', 'join_date'], name='core_member_gym_id_79dd64_idx'),
        ),
        migrations.AddIndex(
            model_name='coachprofile',
            index=models.Index(fields=['gym', 'is_active'], name='core_coachp_gym_id_a983fd_idx'),
        ),
        migrations.AddIndex(
            model_name='coachprofile',
            index=models.Index(fields=['specialization'], name='core_coachp_special_26b64c_idx'),
        ),
        migrations.AddIndex(
            model_name='coachprofile',
            index=models.Index(fields=['gym', 'hire_date'], name='core_coachp_gym_id_c0fd64_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['gym', 'is_active'], name='core_branch_gym_id_378800_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['code'], name='core_branch_code_b50af7_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['gym', 'created_at'], name='core_branch_gym_id_678b5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('gym', 'name')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['gym', 'action_type', 'created_at'], name='core_auditl_gym_id_df844b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='core_auditl_user_id_413764_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['gym', 'created_at'], name='core_auditl_gym_id_fb659c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'created_at'], name='core_auditl_action__9597a4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['member', 'date'], name='core_attend_member__15e27b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['branch', 'date'], name='core_attend_branch__cb9750_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'check_in_time'], name='core_attend_date_bffac6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['qr_code_scanned'], name='core_attend_qr_code_e6f55a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['member', 'check_in_time'], name='core_attend_member__ad00b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('member', 'date', 'check_in_time')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['gym', 'is_active'], name='core_user_gym_id_9890a1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'gym'], name='core_user_email_b4eade_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['gym', 'created_at'], name='core_user_gym_id_faa93b_idx'),
        ),
    ]
